### ISSUE TITLE
Small texts throws :IndexError: list index out of range

### ISSUE THREAD

**Issue by llazzaro** [finiteautomata/leninanalysis#9]
Traceback (most recent call last):
  File "./cccp.py", line 108, in <module>
    main()
  File "./cccp.py", line 87, in main
    calculate_results()
  File "/home/julian/GitHub/leninanalysis/commands/database.py", line 40, in calculate_results
    results = get_all_analysis(tokens, window_sizes, number_of_words=5000)
  File "/home/julian/GitHub/leninanalysis/information_value/analysis.py", line 57, in get_all_analysis
    return dict(pool.map(get_window_size_analysis, window_sizes))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IndexError: list index out of range

**Comment by llazzaro** [comment]
information_values/analysis.py line 17 
"amount_to_be_taken = int(len(iv_words) \* SUM_THRESHOLD)"

amount_to_be_taken is zero in some cases.
